/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwsLogo: typeof import('./src/components/icons/AwsLogo.vue')['default']
    BIframe: typeof import('./src/components/fintech/BIframe.vue')['default']
    BrandImageMain: typeof import('./src/components/icons/BrandImageMain.vue')['default']
    BrandImageMobile: typeof import('./src/components/icons/BrandImageMobile.vue')['default']
    BrandImageModal: typeof import('./src/components/icons/BrandImageModal.vue')['default']
    BrandImageWrapper: typeof import('./src/components/BrandImageWrapper.vue')['default']
    ContactsDropdown: typeof import('./src/components/navigation/ContactsDropdown.vue')['default']
    DarkModeSwitch: typeof import('./src/components/navigation/DarkModeSwitch.vue')['default']
    DockerLogo: typeof import('./src/components/icons/DockerLogo.vue')['default']
    DsLogo: typeof import('./src/components/icons/DsLogo.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    FinTechPlayground: typeof import('./src/components/FinTechPlayground.vue')['default']
    GisPlayground: typeof import('./src/components/GisPlayground.vue')['default']
    GitHub: typeof import('./src/components/icons/GitHub.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    LinkedIn: typeof import('./src/components/icons/LinkedIn.vue')['default']
    LinkedInBadge: typeof import('./src/components/LinkedInBadge.vue')['default']
    Map: typeof import('./src/components/gis/Map.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    PO_exportXLS: typeof import('./src/components/popovers/PO_exportXLS.vue')['default']
    PostgresLogo: typeof import('./src/components/icons/PostgresLogo.vue')['default']
    PythonLogo: typeof import('./src/components/icons/PythonLogo.vue')['default']
    ReactLogo: typeof import('./src/components/icons/ReactLogo.vue')['default']
    RedisLogo: typeof import('./src/components/icons/RedisLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillSection: typeof import('./src/components/SkillSection.vue')['default']
    SocialLinks: typeof import('./src/components/navigation/SocialLinks.vue')['default']
    SourceLinkedInBadge: typeof import('./src/components/legacy/SourceLinkedInBadge.vue')['default']
    SummaryInfo: typeof import('./src/components/SummaryInfo.vue')['default']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TypeScriptLogo: typeof import('./src/components/icons/TypeScriptLogo.vue')['default']
    VirtTable: typeof import('./src/components/fintech/VirtTable.vue')['default']
    VueLogo: typeof import('./src/components/icons/VueLogo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
